#! /bin/sh

# Copyright (C) 2013 Ivo van Poorten
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

test "$#" -eq 2 || { cat << __EOF__

usage:    rkmisc action outfile

generate a misc "partition"

    nothing
    wipe_all
    wipe_data
    wipe_cache
    wipe_userdata
    wipe_swap
    wipe_udisk
    wipe_pagecache
    clear_account
    update_image=%s
    recover_image=%s

__EOF__
exit
}

dd if=/dev/zero of="$2" bs=4096 count=1024

case "$1" in
    nothing)
        ;;
    wipe_all|wipe_data|wipe_cache|wipe_userdata|wipe_swap|wipe_udisk|wipe_pagecache|clear_account|update_image=*|recover_image=*)
        echo -n "boot-recovery" | dd of="$2" bs=1 seek=$((0x4000)) conv=notrunc
        echo -ne "recovery\012--$1" | dd of="$2" bs=1 seek=$((0x4040)) conv=notrunc
        ;;
    *)
        echo "$0: unknown action $1" >&2
        ;;
esac

